# Generated by Django 5.0.2 on 2024-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0006_post_post_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.CharField(max_length=400, null=True)),
                ('about_image', models.ImageField(upload_to='images/sys/about/')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Slide_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_slide_image', models.ImageField(upload_to='images/sys/home/')),
            ],
        ),
        migrations.AlterField(
            model_name='global_settings',
            name='bg_image',
            field=models.ImageField(default='images/sys/bgs/bg.png', upload_to='images/sys/bgs/uploaded_bgs/'),
        ),
        migrations.AlterField(
            model_name='global_settings',
            name='logo_image',
            field=models.ImageField(default='images/sys/logos/logo.png', upload_to='images/sys/logos/uploaded_logo/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_cover_image',
            field=models.ImageField(null=True, upload_to='images/post/cover/'),
        ),
        migrations.AlterField(
            model_name='post_slide_images',
            name='post_slide_image',
            field=models.ImageField(upload_to='images/post/'),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_slide', models.ManyToManyField(to='app_blog_platform.home_slide_images')),
            ],
        ),
    ]
