# Generated by Django 5.0.2 on 2024-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0007_about_home_slide_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='use_image',
            field=models.BooleanField(default=True),
        ),
    ]
