# Generated by Django 5.0.2 on 2024-03-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0009_home_use_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags_level_2',
            name='parent_tag',
        ),
        migrations.RemoveField(
            model_name='tags_level_3',
            name='parent_tag',
        ),
        migrations.AddField(
            model_name='tags_level_2',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog_platform.tags_level_1'),
        ),
        migrations.AddField(
            model_name='tags_level_3',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog_platform.tags_level_2'),
        ),
    ]
