# Generated by Django 5.0.2 on 2024-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0010_remove_tags_level_2_parent_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
