# Generated by Django 5.0.2 on 2024-02-07 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_Level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_url', models.CharField(default='default.css', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Level_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60)),
                ('parent_tag', models.ManyToManyField(to='app_blog_platform.tags_level_1')),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Level_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60)),
                ('parent_tag', models.ManyToManyField(to='app_blog_platform.tags_level_2')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(default='Post Name', max_length=120)),
                ('post_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_tag_level_2', models.ManyToManyField(to='app_blog_platform.tags_level_2')),
                ('post_tag_level_3', models.ManyToManyField(to='app_blog_platform.tags_level_3')),
            ],
        ),
        migrations.CreateModel(
            name='Global_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='My Blog', max_length=50)),
                ('logo_image', models.ImageField(default='logos/logo.png', upload_to='logos/uploaded_logo')),
                ('bg_image', models.ImageField(default='bgs/bg.png', upload_to='bgs/uploaded_bgs')),
                ('bg_color', models.CharField(default=' ', max_length=50)),
                ('show_author', models.BooleanField(default=False)),
                ('theme', models.ManyToManyField(to='app_blog_platform.theme')),
            ],
        ),
    ]
