# Generated by Django 5.0.2 on 2024-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0002_alter_post_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Slide_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_slide_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_main_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_slide_images',
            field=models.ManyToManyField(to='app_blog_platform.post_slide_images'),
        ),
    ]
