# Generated by Django 5.0.2 on 2024-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_platform', '0004_post_post_main_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag_level_1',
            field=models.ManyToManyField(to='app_blog_platform.tags_level_1'),
        ),
    ]
